services:
  reminder-postgres:
    image: postgres:16.1
    container_name: reminder-postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  reminder-auth:
    build:
      context: auth-service
      target: base
    container_name: reminder-auth
    image: reminder-auth
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./auth-service:/app
